// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qostmxgdteaslyunlvet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvc3RteGdkdGVhc2x5dW5sdmV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTk5MjUsImV4cCI6MjA2Nzk5NTkyNX0.9rCo11mqqv2ReMiEcGgAeek_eF-J8QhI6xpPW1LWTp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});