// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://fhisqbevtkjdcokqeoqa.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoaXNxYmV2dGtqZGNva3Flb3FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA5MTI2NDYsImV4cCI6MjA0NjQ4ODY0Nn0.-z2k-4pV0z55N78weRzw6PC_tr6C9NW-m1-YY0UR_yU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);